"""empty message

Revision ID: 81c0a3e1f93e
Revises: c4e79645748c
Create Date: 2021-01-07 17:01:55.050065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c0a3e1f93e'
down_revision = 'c4e79645748c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('friendList')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendList',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"friendList_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('friendIds', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='friendList_userId_fkey'),
    sa.PrimaryKeyConstraint('id', name='friendList_pkey')
    )
    op.drop_table('friends')
    # ### end Alembic commands ###
