"""empty message

Revision ID: 9cbeff75abb8
Revises: 0e718b032d2c
Create Date: 2021-01-15 16:42:56.374757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbeff75abb8'
down_revision = '0e718b032d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_played_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_played_id')
    # ### end Alembic commands ###
