"""empty message

Revision ID: c4e79645748c
Revises: 9609b17c00fd
Create Date: 2021-01-07 16:25:26.624656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e79645748c'
down_revision = '9609b17c00fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letterGrid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('letters', sa.String(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letterGrid')
    # ### end Alembic commands ###
