"""users and letterboards

Revision ID: c7e728a7483a
Revises: 
Create Date: 2021-01-17 12:02:37.139997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e728a7483a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=18), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hash_pass', sa.String(length=255), nullable=False),
    sa.Column('last_logged_in', sa.DateTime(), nullable=False),
    sa.Column('last_played_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('letter_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('letters', sa.JSON(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.Column('orientations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter_board')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
